# Generated by Django 5.0.7 on 2024-12-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='id_rep',
        ),
        migrations.DeleteModel(
            name='Representantes',
        ),
    ]
