# Generated by Django 5.0.7 on 2024-12-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_pacientes_num_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='tipo_doc',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('OT', 'Otro')], default=1, max_length=2, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='tipo_usuario',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Foga', 'Foga')], default=2, max_length=15, verbose_name='Tipo de Usuario'),
            preserve_default=False,
        ),
    ]
