# Generated by Django 5.0.7 on 2024-12-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_horas_id_prof_profesional_num_doc_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Servicio')),
                ('descripcion_servicio', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('servicio_estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('lugares', models.ManyToManyField(blank=True, related_name='servicios', to='administrador.lugares', verbose_name='Lugares donde se ofrece el servicio')),
                ('profesionales', models.ManyToManyField(blank=True, related_name='servicios', to='administrador.profesional', verbose_name='Profesionales que ofrecen este servicio')),
            ],
        ),
    ]
