# Generated by Django 5.0.7 on 2024-12-09 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0009_delete_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas',
            name='fecha_habilitada',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
