# Generated by Django 5.0.7 on 2024-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_remove_servicio_lugares_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='id_lugar',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id_prof',
        ),
        migrations.AddField(
            model_name='servicio',
            name='lugares',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='administrador.lugares', verbose_name='Lugares Asociados'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='profesionales',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='administrador.profesional', verbose_name='Profesionales Asociados'),
        ),
    ]
