# Generated by Django 5.0.7 on 2024-12-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_remove_servicio_id_lugar_remove_servicio_id_prof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='lugares',
        ),
        migrations.AddField(
            model_name='servicio',
            name='lugares',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='administrador.lugares', verbose_name='Lugares Asociados'),
        ),
    ]
