# Generated by Django 5.0.7 on 2024-12-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_remove_servicio_lugares_servicio_lugares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='lugares',
        ),
        migrations.AddField(
            model_name='servicio',
            name='lugares',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='administrador.lugares', verbose_name='Lugares Asociados'),
        ),
    ]
