# Generated by Django 5.1.4 on 2024-12-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_alter_horas_horas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='horas_estado',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
    ]
