# Generated by Django 5.1.4 on 2024-12-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0016_alter_horas_horas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(max_length=255, verbose_name='Nombre del Servicio'),
        ),
    ]
