# Generated by Django 5.1.4 on 2025-01-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0021_remove_consultorio_altura_con_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='peso_con',
        ),
        migrations.AddField(
            model_name='consultorio',
            name='nota_con',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
