# Generated by Django 5.0.7 on 2024-12-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_remove_servicio_lugares_servicio_lugares'),
        ('entrarSistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearcuenta',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.pacientes', verbose_name='Paciente asociado'),
        ),
    ]
