# Generated by Django 5.0.7 on 2024-12-09 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_servicio'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='id_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='administrador.servicio'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='citas_estado',
            field=models.BooleanField(default=True, verbose_name='Estado activo de la cita'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='dia_cit',
            field=models.DateField(verbose_name='Día de la cita'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='estado_cita',
            field=models.CharField(max_length=100, verbose_name='Estado de la cita'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='nota_cit',
            field=models.TextField(verbose_name='Nota adicional'),
        ),
    ]
