# Generated by Django 5.0.7 on 2024-12-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_remove_servicio_lugares_servicio_lugares'),
        ('usuario', '0002_citas_id_servicio_alter_citas_citas_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='id_hora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.horas'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='id_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.lugares'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='id_pac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.pacientes'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='id_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='administrador.servicio'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
