# Generated by Django 5.0.7 on 2024-12-03 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id_cit', models.AutoField(primary_key=True, serialize=False)),
                ('dia_cit', models.DateField()),
                ('nota_cit', models.TextField()),
                ('estado_cita', models.CharField(max_length=100)),
                ('citas_estado', models.BooleanField(default=True)),
                ('id_hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.horas')),
                ('id_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.lugares')),
                ('id_pac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.pacientes')),
                ('id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
