# Generated by Django 5.0.7 on 2024-12-12 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_remove_servicio_lugares_servicio_lugares'),
        ('usuario', '0004_alter_citas_id_hora_alter_citas_id_lugar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCitas',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('id_usu', models.IntegerField(blank=True, null=True, verbose_name='ID Usuario')),
                ('nombre_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('id_prof', models.IntegerField(blank=True, null=True, verbose_name='ID Profesional')),
                ('nombre_prof', models.CharField(blank=True, max_length=255, null=True)),
                ('especialidad_prof', models.CharField(blank=True, max_length=255, null=True)),
                ('id_lugar', models.IntegerField(blank=True, null=True, verbose_name='ID Lugar')),
                ('nombre_lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('id_hora', models.IntegerField(blank=True, null=True, verbose_name='ID Hora')),
                ('inicio_hora', models.TimeField(blank=True, null=True)),
                ('final_hora', models.TimeField(blank=True, null=True)),
                ('id_pac', models.IntegerField(blank=True, null=True, verbose_name='ID Paciente')),
                ('nombre_pac', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_doc_pac', models.CharField(blank=True, max_length=2, null=True)),
                ('num_doc_pac', models.CharField(blank=True, max_length=20, null=True)),
                ('id_servicio', models.IntegerField(blank=True, null=True, verbose_name='ID Servicio')),
                ('nombre_servicio', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_cit', models.DateField(verbose_name='Día de la cita')),
                ('nota_cit', models.TextField(verbose_name='Nota adicional')),
                ('estado_cita', models.CharField(max_length=100, verbose_name='Estado de la cita')),
                ('citas_estado', models.BooleanField(default=True, verbose_name='Estado activo de la cita')),
                ('fecha_historico', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.AddField(
            model_name='citas',
            name='id_prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.profesional'),
        ),
    ]
