# Generated by Django 5.0.7 on 2024-12-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_historicocitas_citas_id_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='estado_cita',
            field=models.CharField(default='Sin confirmar', max_length=100, verbose_name='Estado de la cita'),
        ),
    ]
