# Generated by Django 5.0.7 on 2024-12-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_citas_estado_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='estado_cita',
            field=models.CharField(max_length=100, verbose_name='Estado de la cita'),
        ),
    ]
