# Generated by Django 5.0.7 on 2024-12-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='id_cit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.citas'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.horas'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='lugar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.lugares'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.profesional'),
        ),
        migrations.AddField(
            model_name='consultorio',
            name='id_prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultorios', to='administrador.profesional'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='id_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='administrador.representantes', verbose_name='Representante'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('profesional', 'hora', 'fecha_habilitada', 'lugar')},
        ),
    ]
