# Generated by Django 5.0.7 on 2024-12-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_remove_pacientes_id_rep_delete_representantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='num_doc',
            field=models.CharField(default=1054988878, max_length=20, unique=True, verbose_name='Número de Documento'),
            preserve_default=False,
        ),
    ]
