# Generated by Django 5.0.7 on 2024-12-07 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_pacientes_direccion_pacientes_tipo_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas',
            name='id_prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Horas', to='administrador.profesional'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='num_doc_prof',
            field=models.CharField(default=2, max_length=20, unique=True, verbose_name='Número de Documento'),
            preserve_default=False,
        ),
    ]
