# Generated by Django 5.0.7 on 2024-12-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_alter_profesional_email_prof_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
