# Generated by Django 5.0.7 on 2024-12-10 13:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0010_horas_fecha_habilitada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='lugares',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='profesionales',
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Servicio', to='administrador.lugares', verbose_name='Lugar Asociado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='id_prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Servicio', to='administrador.profesional', verbose_name='Profesional Asociado'),
        ),
        migrations.AlterField(
            model_name='horas',
            name='fecha_habilitada',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Habilitada'),
        ),
        migrations.AlterField(
            model_name='horas',
            name='final_hora',
            field=models.TimeField(verbose_name='Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='horas',
            name='horas_estado',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='horas',
            name='id_prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Horas', to='administrador.profesional', verbose_name='Profesional Asociado'),
        ),
        migrations.AlterField(
            model_name='horas',
            name='inicio_hora',
            field=models.TimeField(verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='id_prof',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
