# Generated by Django 5.1.4 on 2024-12-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0014_remove_servicio_lugares_servicio_lugares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas',
            name='horas_estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado'),
        ),
    ]
