# Generated by Django 5.1.4 on 2024-12-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0017_alter_servicio_nombre_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Servicio'),
        ),
    ]
