# Generated by Django 5.1.4 on 2024-12-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0018_alter_servicio_nombre_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='lugares',
        ),
        migrations.AddField(
            model_name='profesional',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='administrador.lugares', verbose_name='Lugar Asociado'),
        ),
    ]
