# Generated by Django 5.1.4 on 2024-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_remove_servicio_lugares_profesional_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='lugar',
        ),
        migrations.AddField(
            model_name='profesional',
            name='lugares',
            field=models.ManyToManyField(related_name='profesionales', to='administrador.lugares', verbose_name='Lugares Asociados'),
        ),
    ]
